# Generated by Django 3.0.6 on 2020-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='domain',
            field=models.URLField(blank=True, help_text='e.g. https://beta.eosform.app', null=True, verbose_name='Site Domain'),
        ),
    ]
