# Generated by Django 3.0.6 on 2020-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_settings_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='eosgate',
            field=models.URLField(blank=True, help_text='e.g. http://localhost:8080', null=True, verbose_name='EOSGate URI'),
        ),
    ]
