# Generated by Django 3.0.6 on 2020-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_settings_eosgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='eos_node_uri',
            field=models.URLField(blank=True, help_text='e.g. https://api.testnet.eos.io', null=True, verbose_name='EOS Node URI'),
        ),
    ]
