# Generated by Django 3.0.6 on 2020-05-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_settings_eos_node_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='eos_account',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='EOS Account'),
        ),
    ]
