# Generated by Django 3.0.6 on 2020-05-16 23:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import surveys.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UID will be used during EOS upload', unique=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text="question's help text", null=True, verbose_name='Description')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'EMAIL'), (2, 'PHONE'), (3, 'SHORT_TEXT'), (4, 'LONG_TEXT'), (5, 'NUMBER'), (6, 'OPTIONS'), (7, 'CHECKBOXES')], default=surveys.models.QuestionType['SHORT_TEXT'], verbose_name='Question Type')),
                ('is_required', models.BooleanField(default=True, help_text='Question must be answered in order to submit response', verbose_name='Is required?')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey', verbose_name='Question')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
