# Generated by Django 3.0.6 on 2020-05-24 19:19

from django.db import migrations, models
import surveys.utils


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='uid',
            field=models.CharField(db_index=True, default=surveys.utils.gen_eos_username, editable=False, help_text='UID will be used during EOS upload', max_length=12, unique=True),
        ),
    ]
