# Generated by Django 3.0.6 on 2020-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='txid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Transaction ID'),
        ),
    ]
