# Generated by Django 3.0.6 on 2020-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_participation_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='txid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Transaction ID'),
        ),
    ]
